## NumPy Basics

In [18]:
import numpy as np 
import json

array = np.array([10, 20, 30, 40, 50])

print(f"""
      array shape: {array.shape},
      array size: {array.size},
      array dimension: {array.ndim},
      array type: {array.dtype},
      array: {array}
      """)


zero_array = np.zeros((3, 4))
print(f"""
      array shape: {zero_array.shape},
      array size: {zero_array.size},
      array dimension: {zero_array.ndim},
      array type: {zero_array.dtype},
      array: {zero_array}
      """)

one_array = np.ones((2, 2))
print(f"""
      array shape: {one_array.shape},
      array size: {one_array.size},
      array dimension: {one_array.ndim},
      array type: {one_array.dtype},
      array: {one_array}
      """)

number_massive = np.arange(5, 25, 5)
print(f"""
      array shape: {number_massive.shape},
      array size: {number_massive.size},
      array dimension: {number_massive.ndim},
      array type: {number_massive.dtype},
      array: {number_massive}
      """)

equable_array = np.linspace(0, 1, 7)
print(f"""
      array shape: {equable_array.shape},
      array size: {equable_array.size},
      array dimension: {equable_array.ndim},
      array type: {equable_array.dtype},
      array: {equable_array}
      """)




      array shape: (5,),
      array size: 5,
      array dimension: 1,
      array type: int64,
      array: [10 20 30 40 50]
      

      array shape: (3, 4),
      array size: 12,
      array dimension: 2,
      array type: float64,
      array: [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
      

      array shape: (2, 2),
      array size: 4,
      array dimension: 2,
      array type: float64,
      array: [[1. 1.]
 [1. 1.]]
      

      array shape: (4,),
      array size: 4,
      array dimension: 1,
      array type: int64,
      array: [ 5 10 15 20]
      

      array shape: (7,),
      array size: 7,
      array dimension: 1,
      array type: float64,
      array: [0.         0.16666667 0.33333333 0.5        0.66666667 0.83333333
 1.        ]
      


## Indexing and slicing in NumPy.

In [ ]:
from pprint import pprint
array = np.array([5, 10, 15, 20, 25, 30, 35])
response1 = {
    'first_elememt': array[0],
    'last_element': array[-1],
    'slice_from_2_to_5': array[2:6],
    'each_second_elem': array[::2]
}
pprint(response1)

{'each_second_elem': array([ 5, 15, 25, 35]),
 'first_elememt': np.int64(5),
 'last_element': np.int64(35),
 'slice_from_2_to_5': array([15, 20, 25, 30])}


In [33]:
mat = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

response2 = {
    '2:3': mat[1, 2],
    'col_1': mat[0:, 0],
    'col_[3,4]': mat[0:, 2:4],
    'sub_matrix': mat[0:2, 0:3]
}

pprint(response2)

{'2:3': np.int64(7),
 'col_1': array([1, 5, 9]),
 'col_[3,4]': array([[ 3,  4],
       [ 7,  8],
       [11, 12]]),
 'sub_matrix': array([[1, 2, 3],
       [5, 6, 7]])}


## Changing the shape of arrays in NumPy.

In [38]:
array = np.arange(1, 17)
new_array = array.reshape(4, 4)

flatten_array = array.flatten()

ravel_array = array.ravel()

ravel_array[0] = 99

response3 = {
    'array': array,
    'reshaped array': new_array,
    'flatten array(copy)': array,
    'ravel array(origin)': ravel_array,
    'origin array': array
}

pprint(response3, indent=4)


{   'array': array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16]),
    'flatten array(copy)': array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16]),
    'origin array': array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16]),
    'ravel array(origin)': array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16]),
    'reshaped array': array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])}


## Basic array operations and universal functions (ufuncs) in NumPy

In [62]:
a = np.array([1, 2, 3, 4, 5])

b  = np.array([5, 4, 3, 2, 1])

response4 = {
    'sum': a + b,
    'sub': a - b,
    'multy': a * b,
    'diff': a / b,
    'sqrt': np.sqrt(a),
    'log': np.log(a),
    'exp': np.exp(a),
    'sin': np.sin(a),
}


mat = np.array([[1, 2, 3],
              [4, 5, 6]])

response5 = {
    'cols sum': mat.sum(axis=0),
    'rows sum': mat.sum(axis=1),
    'max': mat.max(),
    'min': mat.min(),
    'avg': mat.mean(),
    'std': mat.std()
}

pprint(response4, indent=4, sort_dicts=False)
print()
pprint(response5, indent=4, sort_dicts=False)


{   'sum': array([6, 6, 6, 6, 6]),
    'sub': array([-4, -2,  0,  2,  4]),
    'multy': array([5, 8, 9, 8, 5]),
    'diff': array([0.2, 0.5, 1. , 2. , 5. ]),
    'sqrt': array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798]),
    'log': array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791]),
    'exp': array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ]),
    'sin': array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])}

{   'cols sum': array([5, 7, 9]),
    'rows sum': array([ 6, 15]),
    'max': np.int64(6),
    'min': np.int64(1),
    'avg': np.float64(3.5),
    'std': np.float64(1.707825127659933)}


## Masks, conditions, and array filtering in NumPy.

In [72]:
arr = np.array([1, 2, 3, 4, 5])
mask = arr > 3 # filter elements in arr

arr = np.array([5, 10, 15, 20, 25, 30])

response6 = {
    'mask_15': arr[arr > 15],
    'mask_[10, 25]': arr[(arr > 10) & (arr < 25)],
    'index_gt_20': np.where(arr > 20),
}

mat = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

mat1 = mat.copy()

mat1[mat1 < 5] = 0

response7 = {
    'elem_gt_4': mat[mat > 4],
    'elem_index_3': np.where(mat % 3 == 0),
    'replace_elements': mat1,
}

pprint(response6, indent=False, sort_dicts=False)
pprint(response7, indent=False, sort_dicts=False)



{'mask_15': array([20, 25, 30]),
'mask_[10, 25]': array([15, 20]),
'index_gt_20': (array([4, 5]),)}
{'elem_gt_4': array([5, 6, 7, 8, 9]),
'elem_index_3': (array([0, 1, 2]), array([2, 2, 2])),
'replace_elements': array([[0, 0, 0],
       [0, 5, 6],
       [7, 8, 9]])}


## Broadcasting in NumPy

In [78]:
mat = np.array([[1,2,3],
                [4,5,6]])
vec = np.array([10, 20, 30])

a = np.array([[1], [2], [3]])
b = np.array([10, 20, 30])

c = np.array([1, 2, 3])

response8 = {
    'maxtrix + vector': mat + vec,
    'extends two arrays': a + b,
    'broadcasting with numbers': c + 5,
}

pprint(response8, indent=4, sort_dicts=False)

{   'maxtrix + vector': array([[11, 22, 33],
       [14, 25, 36]]),
    'extends two arrays': array([[11, 21, 31],
       [12, 22, 32],
       [13, 23, 33]]),
    'broadcasting with numbers': array([6, 7, 8])}


## NumPy Random

In [84]:
array = np.random.randint(1, 100, size=(3,3))

array2 = np.arange(1, 21)
array_choices = np.random.choice(array2, size=4, replace=True)


response9 = {
    'random array': array,
    'choices array': array_choices
}

pprint(response9, indent=4, sort_dicts=False)


{   'random array': array([[42, 75, 67],
       [94, 24, 78],
       [74, 67, 98]]),
    'choices array': array([ 7, 17, 18, 17])}


## Matrices and Linear algebra in NumPy

In [106]:
# Евклидова норма
v = [3, 4]
A = np.array([
    [1, 2], 
    [3, 4]
])

B = np.array([
    [1, 2], 
    [2, 4]
])

C = np.array([
    [2, 3], 
    [1, 4]
])

# System of linear equations
D = np.array([[3, 2], [1, -1]])
b = np.array([12, 1])

# Eigenvalues ​​and Eigenvectors
A1 = np.array([[4, -2],
              [1,  1]])

values, vectors = np.linalg.eig(A1)

# Inverse matrix
B1 = np.array([[2, 1], [7, 4]])

# Mult matrix
C1 = np.array([[1,2,3], [4,5,6]])

# Grama matrix
G = np.random.randint(1, 100, size=(3,3))

O = np.array([[0, -1],
 [1,  0]])

# SVD
N = np.array([[3, 1],
              [1, 3]])

U, S, Vt = np.linalg.svd(N)

# Calculate 
matr = np.random.randint(1, 10, size=(4,4))




response10 = {
    'LinAlg norm': int(np.linalg.norm(v)),
    'Det': int(np.linalg.det(A)),
    'Det≠0_B': 'НЕвырожденная' if np.linalg.det(B) != 0 else 'Вырожденная',
    'Det≠0_C': 'НЕвырожденная' if np.linalg.det(C) != 0 else 'Вырожденная',
    'system': np.linalg.solve(D, b),
    'eig_val and vectors': (values, vectors),
    'Inverse matrix': np.linalg.inv(B1),
    'Mult matrix': C1 @ C1.T, 
    'Grama matrix': G.T @ G,
    'Check ortogonal': 'Ортогональная' if np.allclose(O.T @ O, np.eye(2)) else 'Не оргонональная',
    'SVD': True if np.allclose(U @ np.diag(S) @ Vt, N) else False
    
}

matrix_result = {
    'matrix': matr,
    'inverse matrix': np.linalg.inv(matr),
    'det': np.linalg.det(matr),
    'rank': np.linalg.matrix_rank(matr)
}

pprint(response10, indent=4, sort_dicts=False)
print()
pprint(matrix_result, indent=4, sort_dicts=False)


{   'LinAlg norm': 5,
    'Det': -2,
    'Det≠0_B': 'Вырожденная',
    'Det≠0_C': 'НЕвырожденная',
    'system': array([2.8, 1.8]),
    'eig_val and vectors': (   array([3., 2.]),
                               array([[0.89442719, 0.70710678],
       [0.4472136 , 0.70710678]])),
    'Inverse matrix': array([[ 4., -1.],
       [-7.,  2.]]),
    'Mult matrix': array([[14, 32],
       [32, 77]]),
    'Grama matrix': array([[ 5393,  3994,  3362],
       [ 3994,  3750,  5104],
       [ 3362,  5104, 10772]]),
    'Check ortogonal': 'Ортогональная',
    'SVD': True}

{   'matrix': array([[4, 6, 4, 6],
       [9, 1, 9, 2],
       [8, 8, 9, 3],
       [9, 1, 9, 5]]),
    'inverse matrix': array([[ 1.26      ,  2.25333333, -1.        , -1.81333333],
       [ 0.18      ,  0.22666667,  0.        , -0.30666667],
       [-1.28      , -2.09333333,  1.        ,  1.77333333],
       [ 0.        , -0.33333333,  0.        ,  0.33333333]]),
    'det': np.float64(-150.00000000000009),
    'rank': np.int64(

In [110]:
def check_linear_dependence_rows(mat):
    """
    Проверяет линейную зависимость строк матрицы.

    Параметр:
        mat (np.ndarray): матрица размером m x n

    Возвращает:
        True, если строки линейно зависимы
        False, если строки линейно независимы
    """
    rank = np.linalg.matrix_rank(mat)
    n_rows = mat.shape[0]
    return rank < n_rows
    
    
response11 = {
        'dependence': 'Depend' if check_linear_dependence_rows(matr) else 'InDepend'
    }

pprint(response11, indent=4, sort_dicts=False)
    
    

{'dependence': 'InDepend'}


## Merging and splitting arrays

### Merging arrays

In [ ]:
a = np.array([(1,2), (3,4)])
b = np.array([(5,6), (7,8)])


# Merging arrays
ab_horizontal = np.hstack((a, b))
ab_vertical = np.vstack((a, b))


response12 = {
    'A': a,
    'B': b,
    'merge_horizontal': ab_horizontal,
    'merge_vertical': ab_vertical,
}

pprint(response12, indent=4, sort_dicts=False)



{   'A': array([[1, 2],
       [3, 4]]),
    'B': array([[5, 6],
       [7, 8]]),
    'merge_horizontal': array([[1, 2, 5, 6],
       [3, 4, 7, 8]]),
    'merge_vertical': array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])}


In [ ]:
c = np.fromiter(range(18), dtype='int32')
d = np.fromiter(range(18, 36), dtype='int32')
c.resize(3, 3, 2)
d.resize(3, 3, 2)

# Merging arrays
cd_horizontal = np.hstack([c, d])
cd_horizontal = np.vstack([c, d])


response13 = {
    'C': c,
    'D': d,
    'CD_horizontal': cd_horizontal,
    'CD_vertical': cd_horizontal
}


pprint(response13, indent=4, sort_dicts=False)


{   'C': array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]]], dtype=int32),
    'D': array([[[18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29]],

       [[30, 31],
        [32, 33],
        [34, 35]]], dtype=int32),
    'CD_horizontal': array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29]],

       [[30, 31],
        [32, 33],
        [34, 35]]], dtype=int32),
    'CD_vertical': array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]],

    

In [ ]:
# Merging arrays by columns
a = np.array([(1,2), (3,4)])
b = np.array([(5,6), (7,8)])

response14 = {
    'A': a,
    'B': b,
    'merge_by_columns': np.column_stack([a, b]), 
    'concatenate_by_rows': np.concatenate([a, b], axis=0),
    'concatenate_by_columns': np.concatenate([a, b], axis=1)
}

pprint(response14, indent=4, sort_dicts=False)

{   'A': array([[1, 2],
       [3, 4]]),
    'B': array([[5, 6],
       [7, 8]]),
    'merge_by_columns': array([[1, 2, 5, 6],
       [3, 4, 7, 8]]),
    'concatenate_by_rows': array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]]),
    'concatenate_by_columns': array([[1, 2, 5, 6],
       [3, 4, 7, 8]])}


In [ ]:
# r_ and c_ examples
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

respionse15 = {
    'A': a,
    'B': b,
    'r_': np.r_[a, b],
    'c_': np.c_[a, b],
    'example-1': np.r_[ [1, 2, 3], 4, 5],
    'example-2': np.r_[1:9, 90, 100, [1, 2, 3]],
}

pprint(respionse15, indent=4, sort_dicts=False)

{   'A': array([1, 2, 3]),
    'B': array([4, 5, 6]),
    'r_': array([1, 2, 3, 4, 5, 6]),
    'c_': array([[1, 4],
       [2, 5],
       [3, 6]]),
    'example-1': array([1, 2, 3, 4, 5]),
    'example-2': array([  1,   2,   3,   4,   5,   6,   7,   8,  90, 100,   1,   2,   3])}


### Splitting arrays

In [158]:
a = np.arange(10)

c = np.random.randint(0, 9, size=(4,4))
d = np.random.randint(0, 9, size=(4,4))

respionse16 = {
    'A': a,
    'vertical_split': np.vsplit(c, 2),
    'C': c,    
    'split_c': np.array_split(c, 3)
}

pprint(respionse16, indent=4, sort_dicts=False)

{   'A': array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
    'vertical_split': [   array([[3, 5, 3, 6],
       [4, 7, 1, 3]]),
                          array([[5, 1, 2, 7],
       [5, 5, 7, 8]])],
    'C': array([[3, 5, 3, 6],
       [4, 7, 1, 3],
       [5, 1, 2, 7],
       [5, 5, 7, 8]]),
    'split_c': [   array([[3, 5, 3, 6],
       [4, 7, 1, 3]]),
                   array([[5, 1, 2, 7]]),
                   array([[5, 5, 7, 8]])]}
